### ISSUE TITLE
Wrap a material-ui dialog with formsy.form

### ISSUE THREAD

**Issue by Mokto** [mbrookes/formsy-material-ui#102]
Hi,

I do not if this is formsy-material-ui or formsy-react related, but I would like to wrap all my dialog with Formsy.form so I can set type='submit' on dialog actions.

the form tag is not created so it does not work.

I hope that I am understandle enough ^^

**Comment by jonmase** [comment]
Hi Mokto,

Did you find a solution to this? I've got the same problem, and am currently 'fixing' it by just putting my Formsy.Form within my dialog and then adding buttons manually at the bottom of the form, rather than using the actions attribute of the dialog. This is not ideal, but was a quick fix for the time being. I've also styled my manually added buttons to look like they would if they were using the dialog actions attribute. 

I found this - http://stackoverflow.com/questions/36263488/form-in-material-ui-dialog-using-react - which explains the reason for the problem, and points to a possible solution, using the (unsupported in IE) HTML5 form attribute, here: https://www.tjvantoll.com/2013/07/10/creating-a-jquery-ui-dialog-with-a-submit-button/. I haven't actually tried it, because I already have something that works for now, and I'd prefer to avoid cluttering things up with JQuery + polyfills, and I'm hoping there's an obvious solution that I've missed!

Jon

**Comment by Mokto** [comment]
Yeah, I did what you did, creating floating buttons at the end of the dialog.

Gonna try your form attribute soon, thx !

**Comment by Mokto** [comment]
@jonmase

Thanks, your form attribute works !

As I'm using electron, I do not care about browser compatibility but your can use the polyfill your article provides.

Since it's not a perfect solution, I'll let this issue open.

**Comment by adamsidiali** [comment]
You can manually submit the formsy form from outside of the form by assigning the ref to your component like: 
```
<Formsy.Form
      ref={(form) => {
        this.formsyForm = form;
      }}
      onSubmit={(options) => { console.log(options); // logs form values }}
>
```
and then just call `this.formsyForm.submit()` from any other `onClick` callback in your component.

**Comment by mbrookes** [comment]
Thanks @adamsidiali .

**Comment by hubgit** [comment]
The problem with having the Dialog buttons outside the form is that pressing Enter no longer submits the form when there's more than one text input.

The only workaround seems to be to add a hidden submit `button` to the form?

**Comment by rojobuffalo** [comment]
@hubgit which element are you `focused` on when hitting the return key?

**Comment by hubgit** [comment]
@rojobuffalo the first of two text (FormsyText) inputs, in a form with no `button`.

**Comment by rojobuffalo** [comment]
Thanks for the details. This doesn't sound like a common use-case. My opinion here is that what you're wanting should be achievable, but doesn't need to be written into this API. You should be able to get what you want by handling `onKeyPress`. We can leave it open though to see if other people want this behavior.
