### ISSUE TITLE
[FormsyDate] defaultDate is not valid for required

### ISSUE THREAD

**Issue by lethanhquang** [mbrookes/formsy-material-ui#29]
Hi everyone, 

Here my component, I try to set defaultDate is `minDate` but the form is still invalid cause the value of `start_date_time` still null until I make a change on this. Have you had any idea for this? 

```
<FormsyDate
        required
        fullWidth
        disableYearSelection
        minDate={minDate}
        defaultDate={minDate}
        formatDate={this.handleFormatDate}
        name="start_date_time"
        floatingLabelText="Start date" />```

**Comment by mbrookes** [comment]
I suspect this is probably similar to #21. I'll take a look.

**Comment by mbrookes** [comment]
Try `value` instead of `defaultDate`. Formsy expects the default to be in 'value' prop, and it so happens DatePicker also supports this prop; so unlike FormsyText, there was no need to change FormsyDate to internally map `value` to `defaultDate`.

Material-UI has _the_ most inconsistent API! :hankey:

**Comment by mbrookes** [comment]
Tested and confirmed working as described.
