### ISSUE TITLE
Prefilling or Initializing does not work using this.ref.form.reset(model)

### ISSUE THREAD

**Issue by vijayrawatsan** [mbrookes/formsy-material-ui#9]
I am using formsy-react 0.14.1 & formsy-material-ui 0.2.2
```javascript
componentDidMount: function(nextProps) {
        this.resetForm({
            'name': 'asd',
            'email': 'asd@asd.com'
        });
    },
resetForm: function (model) {
        this.refs.form.reset(model);
    },
submitForm: function (model) {
        console.log(model);
    } 
```
When I submit I could see asd and asd@asd.com, but I can not see the value in the form itself.

**Comment by mbrookes** [comment]
Thanks for letting me know - there are quite a few of these sorts of issues outside of the basic use case. I hope to get some time to review them over the next week or two, but if you had an opportunity to look at this particular issue, and let me now what you think the cause is, that would be a great help.

**Comment by vijayrawatsan** [comment]
This seems to have fixed the issue for textfield. 
https://github.com/mbrookes/formsy-material-ui/pull/10
If you think this is a good fix. Please do merge it and create a release. So that I could pull the latest repo from npm.

Thanks
