### ISSUE TITLE
Typing in FormsyText doesn't update Form validity

### ISSUE THREAD

**Issue by damonmaria** [mbrookes/formsy-material-ui#97]
If I have a `FormsyText` with `required=true` then typing in the text field does not fire the form's `onValid()` and `form.state.isValid` is `false`. On when the text field blurs do these update.

So at the moment I can't enable and disable the form's submit button based on the form being valid.

**Comment by lefnire** [comment]
Same issue. Prior version updated `isValid` on field update; so this seems like a bug rather than design.

**Comment by mbrookes** [comment]
I suspect we lost something in the move back from stateless to stateful to solve a performance issue. (And it may well be that validating on every key press was the cause of that issue - I honestly didn't dig into it.)

If someone wants to have a go at solving this, please jump in.

**Comment by lefnire** [comment]
Just spent an hour fiddling; unfortunately I'm in over my head, and probably won't have the time to get up-to-date. FWIW if performance every keypress causes a performance issue, perhaps debounce could be used.

`npm i --save lodash.debounce`
```javascript
import debounce from 'lodash.debounce';
...
handleChange = debounce((event) => {
  ...
}, 500);
```

**Comment by krizka** [comment]
What is the version before this optimisations? seems related with form resetting too.

**Comment by mbrookes** [comment]
@lefnire - good idea, I'll keep that in mind.

**Comment by Sabst** [comment]
Does anyone have a workaround? This has a strong visual impact : forms are not so reactive anymore (have to move to another field to update the submit button)
I'm using material-ui 0.15.0, formsy-material-ui 0.4.3 and formsy-react 0.18.0.

**Comment by ochervak** [comment]
is there is any updates

**Comment by Sabst** [comment]
There is probably an obvious fix but I could not find it... looking at alternative libs now.

**Comment by ochervak** [comment]
sounds pretty bad. i used this library a lot in my project...

**Comment by ochervak** [comment]
@Sabst looks like i found the "proper" solution (troll face).
I fixed issue for TextField element with next steps: 
I change `handleChange` function to next form:
```
handleChange: function handleChange(event) {
    this.setState({
      value: event.currentTarget.value
    });
    this.setValue(event.currentTarget.value);
    if (this.props.onChange) this.props.onChange(event);
  },
```

I'm not sure how it affect on performance but it definitely fixed this issue

**Comment by ochervak** [comment]
maybe PR for this ?

**Comment by Sabst** [comment]
@ochervak Well done!
Now, while checking other pending PRs, I came across this one: https://github.com/mbrookes/formsy-material-ui/pull/103/commits
It has the advantage of implementing your fix while - just in case - keeping the broken behavior by default.

**Comment by damonmaria** [comment]
Regarding which pull request to use: as far as I'm aware this is a regression and so the default behaviour should be to update on each key press. But there has also been discussion about updating each key press possibly being a performance issue. So maybe having it an option like in PR #103 but with on being the default. Has anyone checked or noticed performance problems?

**Comment by ochervak** [comment]
please, use #103 PR. Since having all TextField controlled is really performance critical part, however i think we need another solution...

**Comment by mbrookes** [comment]
The ideal scenario is that the the form validity is checked immediately, so the submit button can be enabled without removing focus for the last field (if a text field), but that the error message for the field (if any) is only displayed when the a field loses focus.

This was the behaviour prior to the last major update, but had the performance mentioned.

**Comment by mbrookes** [comment]
I haven't tested every scenario (e.g. externally controlled), but tihs seems to work as desired for uncontrolled, and does'n have the lag previously experienced:

```js
  handleChange: function handleChange(event) {
    this.setState({
      value: event.currentTarget.value,
    });
    if (this.isValidValue(event.target.value)) {
      this.setValue(event.target.value);
    }
    if (this.props.onChange) this.props.onChange(event, event.currentTarget.value);
  },
```

Can everyone check and confirm if this works for your use case?

**Comment by krizka** [comment]
Hello there. Sorry for long silence. My workaround looks like this gist https://gist.github.com/krizka/6be5cd3fd1a200f1dba9de6363dbe63d . Just put it in your project and import instead of FormsyText.js. I use debouncing here to validate values on input change. Unfortunately, verification on every change is slow, so debouncing helps.

**Comment by krizka** [comment]
The gist above also fixes form resetting to empty values instead of `undefined`

**Comment by codeaholicguy** [comment]
@mbrookes Please take a look at https://github.com/mbrookes/formsy-material-ui/pull/103, I tried to test on weak mobile device and it seem ok

**Comment by Sabst** [comment]
I used the gist from @krizka (as it does not require updating the FormsyText code itself) and it worked perfectly.
My forms are quite simple so I cannot say about debounce added value.

**Comment by mbrookes** [comment]
@codeaholicguy @Sabst Please test https://github.com/mbrookes/formsy-material-ui/issues/97#issuecomment-222388623  it doesn't require an extra prop.

**Comment by codeaholicguy** [comment]
@mbrookes so what if I input a valid value, and after I delete or do something to make it invalid, it wont be set, right?

**Comment by Sabst** [comment]
@mbrookes I think you should not test if the value is valid before setting it: it makes sense to display the error as the user types, i.e. always set the value.
If you leave the `isValidValue` test, the error feedback will be display only when the focus of the text field is lost.
Apart from that, I see the same behavior as with @krizka gist. Now shouldn't the debounce be kept anyway for more specific use-cases highlighted in previous comments?
@codeaholicguy: from my tests, the invalid value is set anyway somewhere else (`onBlur/handleBlur`)... but IMO too late as outlined in the first part of this comment.

**Comment by mbrookes** [comment]
@codeaholicguy You're right, I missed that case. We really need to fix up the test suite and get tests working again!

@Sabst 
> it makes sense to display the error as the user types

We tried that in the past - it's horrible UX, because as soon as the user starts typing a valid value that doesn't yet meet all the criteria, they get an error. We could perhaps add a prop to enable that for specific use cases, but I don't think it should be the default behaviour. 

> Now shouldn't the debounce be kept

I don't think it can harm to add it

**Comment by mbrookes** [comment]
> because as soon as the user starts typing a valid value that doesn't yet meet all the criteria, they get an error

Hmm, actually, in conjunction with debounce that might not be so bad, as they'll only get an error when they pause typing, rather than immediately. I'll try it.

**Comment by Sabst** [comment]
@mbrookes 
> I don't think it should be the default behaviour

Ok, I see your point. In my use-case, it appeared more like a useful hint but I agree with you on a more general approach. Will create a new issue for this new prop in case the need is confirmed.
As I set `disabled={!this.state.canSubmit}` on the submit button, do you confirm canSubmit state will be up-to-date, even in @codeaholicguy use-case above?

**Comment by mbrookes** [comment]
@Sabst @codeaholicguy's PR, (which he has added debounce to) does update `canSubmit` after the debounce timeout, both to set and unset it based on the current state of the value, however the 200ms debounce is too short, so you get an error displayed after a momentary pause in typing.

Setting the debounce longer (say 400ms) helps, but then there is a lag before the submit button appears after a correct entry is typed, so I still think the default should be to update `canSubmit` without updating the error, with a prop to enable immediate update of the error with optional debounce timeout.(@codeaholicguys PR's only works in the latter case - if you don't set `updateImmediately`, `canSubmit isn't set until you change focus.).

I installed the old demo to check what the previous behaviour was (I haven't used formsy-material-ui myself for about 6 months since I started dedicating my spare time to Material-UI, and my own project that I was using it for fell by the wayside!).

It seems using `formsy-material-ui@0.3.9` that it works much as https://github.com/mbrookes/formsy-material-ui/issues/97#issuecomment-222388623 does: updating `canSubmit` immediately, but only displaying an error on removing focus from the input element; but with the same issue of not changing `canSubmit` when the value changes from valid to invalid.

Curiously I also don't see the performance issue with that version that others had reported!

**Comment by mbrookes** [comment]
Okay, I took @codeaholicguy's PR, and added some well commented code for the alternate use-case, as well as for controlled use. Take a look.

**Comment by mohithg** [comment]
Facing the same issue.

**Comment by krizka** [comment]
Please @mbrookes look at [my comment](https://github.com/mbrookes/formsy-material-ui/issues/97#issuecomment-222419002) as workaround

**Comment by mbrookes** [comment]
@krizka https://github.com/mbrookes/formsy-material-ui/pull/109

**Comment by stupidisum** [comment]
Looks like the author is busy. Anybody else has access to fix bugs? @mbrookes

**Comment by mbrookes** [comment]
@stupidisum I've added several contributors as collaborators over the last year, but no-one has felt able to be more proactive.

**Comment by codeaholicguy** [comment]
@stupidisum You can take a look at https://github.com/mbrookes/formsy-material-ui/pull/109

**Comment by stupidisum** [comment]
When will you release this? 
Btw, your repo is not containing latest build (the lib dir), so I can't use your latest version from github.

**Comment by stupidisum** [comment]
@codeaholicguy @mbrookes

**Comment by lefnire** [comment]
@stupidisum in a pinch you can add a bit to your own `package.json` to run this module's build step before your own, see my [diff example](https://gist.github.com/lefnire/5784a0ba6793396c408f17d488a79e0d)
